---
- hosts: ansible
  tasks:
  - name: create docker image
    command: docker build -t regapp:latest .
    args:
     chdir: /opt/docker


  - name: create tag to push image on dockerhub
    command: docker tag regapp:latest netcualexandru/regapp:latest

  - name: push docker image
    command: docker push netcualexandru/regapp:latest
